Remove credential helper
```
  ERROR: unable to select packages:
    docker-credential-ecr-login (no such package):
      required by: world[docker-credential-ecr-login]
```